spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring_reactive_demo
      username: root
      password: root@123
      authentication-database: admin
# Change the uat and prod profiles
server:
  port: 8083
---
spring:
  profiles: uat
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
server:
  port: 8080
#---
#spring:
#  profiles: prod
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: localDB